import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Hand-authored sidebar: the curated order is intentional, not autogenerated.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: ['getting-started', 'build-your-first-game'],
    },
    {
      type: 'category',
      label: 'Query Language',
      items: [
        'query-language/reference',
        'query-language/expressions',
        'query-language/data-types',
        'query-language/set-operations',
        'query-language/sql-reference',
        'query-language/compiled-queries',
        'query-language/portable-interpreter',
        'query-language/mutations',
        'query-language/functions',
      ],
    },
    {
      type: 'category',
      label: 'Schema & Data',
      items: [
        'schema/schema-language',
        'schema/schema-tooling',
        'schema/schema-workflow',
        'schema/indexing',
        'schema/schema-migration',
      ],
    },
    {
      type: 'category',
      label: 'Database Engine',
      items: [
        'engine/database-engine',
        'engine/configuration',
        'engine/transactions',
        'engine/concurrency',
        'engine/persistence',
        'engine/encryption-threat-model',
        'engine/backup-restore',
        'engine/production-readiness',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Features',
      items: [
        'advanced/reactive-queries',
        'advanced/procedural-generation',
        'advanced/navigation-editors',
      ],
    },
    {
      type: 'category',
      label: 'Performance',
      items: ['performance/performance-tips', 'performance/pgo'],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      items: [
        'examples/leaderboard',
        'examples/inventory',
        'examples/reporting',
        'examples/quests',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/error-codes', 'reference/glossary', 'reference/troubleshooting'],
    },
  ],
};

export default sidebars;
